#!/usr/bin/env bash

# Use the Prisma engine paths that should already be set in the shell
export PRISMA_MIGRATION_ENGINE_BINARY="${PRISMA_MIGRATION_ENGINE_BINARY}"
export PRISMA_QUERY_ENGINE_BINARY="${PRISMA_QUERY_ENGINE_BINARY}"
export PRISMA_QUERY_ENGINE_LIBRARY="${PRISMA_QUERY_ENGINE_LIBRARY}"
export PRISMA_INTROSPECTION_ENGINE_BINARY="${PRISMA_INTROSPECTION_ENGINE_BINARY}"
export PRISMA_FMT_BINARY="${PRISMA_FMT_BINARY}"
export PRISMA_SCHEMA_ENGINE_BINARY="${PRISMA_SCHEMA_ENGINE_BINARY}"
export PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING="1"
export PRISMA_SKIP_POSTINSTALL_GENERATE="true"

# Run the actual postinstall commands
husky install && turbo run post-install